version: "3"
services:
  mongo:
    image: "mongo:latest"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - APP_ORIGIN=${APP_ORIGIN}
      - API_HOST=${API_HOST}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - CORS_ORIGIN_REGEX=${CORS_ORIGIN_REGEX}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata: